# Generated by Django 3.2.25 on 2024-04-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('height_and_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('bad_habits', models.CharField(blank=True, max_length=100, null=True)),
                ('caesarean', models.CharField(blank=True, max_length=100, null=True)),
                ('children_age', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('blood', models.CharField(blank=True, max_length=100, null=True)),
                ('maried', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, choices=[('created', 'recently created'), ('working', 'we are working'), ('no baby', 'has not baby'), ('WWW', 'wrote WhatsApp, waiting the answer')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[(None, '-----'), ('trash', 'trash'), ('ban', 'ban'), ('primary', 'primary stage'), ('first_visit', 'first visit')], default='primary', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Planned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[(None, '-----'), ('LABORATORY', 'Laboratory')], max_length=15)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Messanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messanger', models.CharField(blank=True, choices=[('TEL', 'Telegram'), ('WTS', 'WhatsApp'), ('VIB', 'Viber')], max_length=3, null=True)),
                ('in_group', models.BooleanField(default=False)),
                ('date_add_in_group', models.DateField(auto_now_add=True)),
                ('mother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_id', models.CharField(max_length=255)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother'),
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
