# Generated by Django 3.2.25 on 2024-03-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('height_and_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('bad_habits', models.CharField(blank=True, max_length=100, null=True)),
                ('caesarean', models.CharField(blank=True, max_length=100, null=True)),
                ('children_age', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('blood', models.CharField(blank=True, max_length=100, null=True)),
                ('maried', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('primary_stage', 'primary stage'),),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, choices=[('', '-'), ('created', 'recently created'), ('working', 'we are working'), ('no baby', 'has not baby'), ('WWW', 'wrote WhatsApp, waiting the answer')], default='', max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
            options={
                'permissions': (('primary_state', 'primary state'),),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[(None, '(Unknown)'), ('Trash', 'trash'), ('Ban', 'ban'), ('Primary', 'initial stage'), ('First Visit', 'first visit')], default='Primary', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Planned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Take tests', 'Analyzes in Shymkent'), ('Doctors', 'Go for doctors'), ('Verifying', 'Extra treatment')], max_length=15, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Messanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messanger', models.CharField(blank=True, choices=[('TEL', 'Telegram'), ('WTS', 'WhatsApp'), ('VIB', 'Viber')], max_length=3, null=True)),
                ('in_group', models.BooleanField(default=False)),
                ('date_add_in_group', models.DateField(auto_now_add=True)),
                ('mother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
