# Generated by Django 3.2.25 on 2024-07-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedQuestionnaire',
            fields=[
            ],
            options={
                'verbose_name': 'Completed questionnaire',
                'verbose_name_plural': 'Completed questionnaires',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
    ]
