# Generated by Django 3.2.23 on 2024-01-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
