# Generated by Django 3.2.23 on 2023-12-20 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherStep1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.AlterField(
            model_name='condition',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('Tests', 'get tested'), ('Dipherelin', 'dipherelin')], max_length=15, null=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
