# Generated by Django 3.2.25 on 2024-04-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanProxy',
            fields=[
            ],
            options={
                'verbose_name': 'MotherBan',
                'verbose_name_plural': 'bans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
    ]
