# Generated by Django 3.2.25 on 2024-03-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'permissions': (('ban_state', 'ban state'),)},
        ),
    ]
