# Generated by Django 3.2.25 on 2024-07-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0002_completedquestionnaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedQuestionnaire',
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
    ]
