# Generated by Django 3.2.25 on 2024-04-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0003_documentproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentProxy',
        ),
    ]
