# Generated by Django 3.2.25 on 2024-07-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0003_auto_20240709_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratorymanager',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='messanger',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='planned',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='state',
            name='mother',
        ),
        migrations.AlterModelOptions(
            name='mother',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
        migrations.DeleteModel(
            name='LaboratoryManager',
        ),
        migrations.DeleteModel(
            name='Messanger',
        ),
        migrations.DeleteModel(
            name='Planned',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother'),
        ),
    ]
