# Generated by Django 3.2.23 on 2024-01-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0003_alter_condition_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(blank=True, choices=[('WT', 'we talk'), ('CYC', 'cycle'), ('DAC', "doesn't answer the call"), ('WWW', 'wrote in WhatsApp and waiting'), ('WTW', 'wrote in Telegram and waiting'), ('NDE', "number doesn't exists"), ('PR', 'pregnant'), ('SIC', 'get sick'), ('HF', 'husband forbids'), ('ECR', 'examines children or relatives'), ('AN', 'another')], max_length=10, null=True),
        ),
    ]
