# Generated by Django 3.2.23 on 2023-12-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0003_auto_20231220_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryVisit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.AlterModelOptions(
            name='mother',
            options={'permissions': [('main_manager_condition_filter_option', 'Can filter mothers by inline on their questionnaire'), ('revoke_mothers', 'Can revoke mothers instance'), ('return_mothers', 'Can return mothers instance'), ('can_view_first_visit_mothers', 'Can view mothers on first visit stage')]},
        ),
        migrations.CreateModel(
            name='Planned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Tests', 'Analyzes in Shymkent'), ('Doctors', 'Go for doctors'), ('Verifying', 'Extra treatment')], max_length=15)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('mother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
