# Generated by Django 3.2.23 on 2023-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0004_auto_20231220_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planned',
            name='plan',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Tests', 'Analyzes in Shymkent'), ('Doctors', 'Go for doctors'), ('Verifying', 'Extra treatment')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Primary', 'get tested'), ('Dipherelin', 'dipherelin')], max_length=15, null=True),
        ),
    ]
