# Generated by Django 3.2.25 on 2024-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0004_delete_documentproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='condition',
            field=models.CharField(blank=True, choices=[('created', 'recently created'), ('working', 'we are working'), ('no baby', 'has not baby'), ('WWW', 'wrote WhatsApp, waiting the answer')], max_length=20, null=True),
        ),
    ]
