# Generated by Django 3.2.25 on 2024-07-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0004_auto_20240711_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother', verbose_name='scheduled_event'),
        ),
    ]
