# Generated by Django 3.2.25 on 2024-07-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0005_alter_scheduledevent_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_event', to='mothers.mother'),
        ),
    ]
