# Generated by Django 3.2.23 on 2024-01-30 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0005_alter_condition_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
