# Generated by Django 3.2.23 on 2023-12-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0005_auto_20231220_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mother',
            options={'permissions': [('to_manager_on_primary_stage', 'Can do all with mother instance without specific actions'), ('revoke_mothers', 'Can revoke mothers instance'), ('return_mothers', 'Can return mothers instance')]},
        ),
    ]
