# Generated by Django 3.2.25 on 2024-07-13 09:41

from django.db import migrations, models
import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0006_alter_scheduledevent_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPlan',
            fields=[
            ],
            options={
                'verbose_name': 'Short Plan',
                'verbose_name_plural': 'Short Plans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[documents.services.validate_max_length]),
        ),
    ]
