# Generated by Django 3.2.25 on 2024-07-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0007_auto_20240713_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortplan',
            options={'verbose_name': 'Short', 'verbose_name_plural': 'Short'},
        ),
    ]
