# Generated by Django 3.2.23 on 2023-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0007_auto_20231222_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
