# Generated by Django 3.2.23 on 2024-02-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0007_alter_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother'),
        ),
    ]
