# Generated by Django 3.2.23 on 2024-02-10 19:45

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0008_alter_comment_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planned',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 10, 19, 45, 50, 715726, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
