# Generated by Django 3.2.23 on 2023-12-22 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0008_alter_condition_scheduled_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mother',
            options={'permissions': [('to_manager_on_primary_stage', 'Can do all with mother instance without specific actions'), ('action_first_visit', 'transfer mothers to the first visit'), ('revoke_mothers', 'Can revoke mothers instance'), ('return_mothers', 'Can return mothers instance')]},
        ),
        migrations.AlterField(
            model_name='condition',
            name='scheduled_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
