# Generated by Django 3.2.25 on 2024-07-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0008_alter_shortplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortplan',
            options={'verbose_name': 'Short Plan', 'verbose_name_plural': 'Short Plans'},
        ),
    ]
