# Generated by Django 4.0 on 2024-07-26 13:29

from django.db import migrations, models
import django.db.models.deletion
import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0009_alter_shortplan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serology', models.FileField(blank=True, null=True, upload_to='serology/')),
                ('cytology', models.FileField(blank=True, null=True, upload_to='cytology/')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoryAndDoctor',
            fields=[
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, validators=[documents.services.validate_max_length])),
                ('scheduled_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('analysis', models.ManyToManyField(related_name='analysis', to='mothers.AnalysisChoice')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to='mothers.mother')),
            ],
        ),
    ]
