# Generated by Django 3.2.23 on 2024-02-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0009_auto_20240210_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
