# Generated by Django 3.2.23 on 2023-12-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0009_auto_20231222_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimaryVisit',
        ),
    ]
