# Generated by Django 3.2.23 on 2023-12-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0010_delete_primaryvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='planned',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
