# Generated by Django 4.0 on 2024-07-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0010_analysischoice_laboratoryanddoctor_laboratory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratoryanddoctor',
            options={'verbose_name': 'Lab', 'verbose_name_plural': 'Labs'},
        ),
    ]
