# Generated by Django 3.2.23 on 2024-02-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0010_stage_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(blank=True, choices=[('', ''), ('created', 'recently created'), ('no baby', 'has not baby'), ('WWW', 'wrote WhatsApp, waiting the answer')], default='', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
