# Generated by Django 3.2.23 on 2024-02-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0011_auto_20240226_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condition',
            new_name='State',
        ),
    ]
