# Generated by Django 3.2.23 on 2023-12-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0011_planned_scheduled_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mother',
            options={'permissions': [('to_manager_on_primary_stage', 'Can do all with mother instance without specific actions'), ('action_first_visit', 'transfer mothers to the first visit'), ('revoke_mothers', 'Can revoke mothers instance'), ('return_mothers', 'Can return mothers instance'), ('to_manager_on_first_stage', 'Can do all with mother instance without specific actions')]},
        ),
    ]
