# Generated by Django 4.0 on 2024-07-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0011_alter_laboratoryanddoctor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='analysis',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='mothers.analysischoice'),
        ),
    ]
