# Generated by Django 4.0 on 2024-07-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0012_remove_laboratory_analysis_laboratory_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='analysis',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='analysis',
            field=models.ManyToManyField(related_name='analysis', to='mothers.AnalysisChoice'),
        ),
    ]
