# Generated by Django 3.2.23 on 2023-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0012_alter_mother_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planned',
            name='plan',
            field=models.CharField(choices=[(None, '(Unknown)'), ('Take tests', 'Analyzes in Shymkent'), ('Doctors', 'Go for doctors'), ('Verifying', 'Extra treatment')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Primary', 'undergoing medical tests'), ('Dipherelin', 'dipherelin')], max_length=15, null=True),
        ),
    ]
