# Generated by Django 3.2.23 on 2023-12-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0013_auto_20231224_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planned',
            name='plan',
            field=models.CharField(blank=True, choices=[(None, '(Unknown)'), ('Take tests', 'Analyzes in Shymkent'), ('Doctors', 'Go for doctors'), ('Verifying', 'Extra treatment')], max_length=15, null=True),
        ),
    ]
