# Generated by Django 4.0 on 2024-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0015_remove_laboratory_cytology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysischoice',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('SEROLOGY', 'Serology'), ('CYTOLOGY', 'Cytology')], max_length=20, null=True),
        ),
    ]
