# Generated by Django 3.2.23 on 2023-12-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0015_alter_mother_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planned',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
