# Generated by Django 4.0 on 2024-07-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0016_alter_analysischoice_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEROLOGY', 'Serology'), ('CYTOLOGY', 'Cytology')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='analysis',
        ),
        migrations.AddField(
            model_name='analysischoice',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_choices', to='mothers.laboratory'),
        ),
        migrations.AlterField(
            model_name='analysischoice',
            name='analysis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.analysistype'),
        ),
    ]
