# Generated by Django 3.2.23 on 2023-12-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0016_auto_20231225_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mother',
            options={'permissions': [('to_manager_on_primary_stage', 'Can do all with mother instance without specific actions'), ('action_first_visit', 'transfer mothers to the first visit'), ('move_to_ban', 'Can banned mother instances'), ('return_mothers', 'Can return mothers instance'), ('to_manager_on_first_stage', 'Can do all with mother instance without specific actions'), ('action_on_primary_stage', 'Return mother on primary stage')]},
        ),
    ]
