# Generated by Django 4.0 on 2024-07-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0017_analysistype_remove_laboratory_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysischoice',
            name='analysis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mothers.analysistype'),
        ),
    ]
