# Generated by Django 3.2.23 on 2023-12-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0017_alter_mother_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='revoked',
            new_name='banned',
        ),
    ]
