# Generated by Django 4.0 on 2024-07-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0018_alter_analysischoice_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='analysis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='mothers.analysistype'),
        ),
        migrations.DeleteModel(
            name='AnalysisChoice',
        ),
    ]
