# Generated by Django 3.2.23 on 2023-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0018_rename_revoked_comment_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
