# Generated by Django 4.2 on 2024-08-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0022_telegrammessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='laboratory',
        ),
        migrations.DeleteModel(
            name='LaboratoryAndDoctor',
        ),
        migrations.CreateModel(
            name='PlannedLaboratory',
            fields=[
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.DeleteModel(
            name='TelegramMessage',
        ),
    ]
