# Generated by Django 4.2 on 2024-08-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0023_remove_telegrammessage_laboratory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mothers.laboratory')),
            ],
        ),
    ]
