# Generated by Django 4.2 on 2024-08-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0024_doctoranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='analysis_types',
            field=models.ManyToManyField(related_name='analysis_types', to='mothers.analysistype'),
        ),
    ]
