# Generated by Django 4.2 on 2024-08-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0026_alter_laboratoryfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mothers.laboratory')),
            ],
        ),
    ]
