# Generated by Django 4.2 on 2024-08-12 11:05

from django.db import migrations, models
import mothers.models.mother


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0028_remove_laboratoryvideo_video_laboratoryvideo_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryvideo',
            name='ultrasound_file',
            field=models.FileField(blank=True, null=True, upload_to=mothers.models.mother.directory_path_file),
        ),
    ]
