# Generated by Django 4.2 on 2024-08-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0030_alter_laboratoryvideo_laboratory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoranswer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctoranswer',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='is_coming',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
