# Generated by Django 4.2 on 2024-08-16 13:21

from django.db import migrations, models
import mothers.models.mother


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0032_doctoranswer_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryfile',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laboratoryfile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=mothers.models.mother.directory_path_video),
        ),
        migrations.AlterField(
            model_name='laboratoryfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mothers.models.mother.directory_path_file),
        ),
        migrations.DeleteModel(
            name='LaboratoryVideo',
        ),
    ]
