# Generated by Django 4.2 on 2024-08-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0033_laboratoryfile_hash_laboratoryfile_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.IntegerField()),
                ('is_posted', models.BooleanField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_laboratory', to='mothers.laboratory')),
            ],
        ),
    ]
