# Generated by Django 4.2 on 2024-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0034_laboratorymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryfile',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
