# Generated by Django 4.2 on 2024-08-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0035_alter_laboratoryfile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
