# Generated by Django 4.2 on 2024-08-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0036_laboratory_is_filled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='is_coming',
            new_name='is_came',
        ),
    ]
