# Generated by Django 3.2.25 on 2024-03-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
        ('gmail_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStage',
            fields=[
                ('stage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mothers.stage')),
            ],
            bases=('mothers.stage',),
        ),
    ]
