# Generated by Django 3.2.25 on 2024-07-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_messages', '0002_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stage',
        ),
    ]
