# Generated by Django 3.2.25 on 2024-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_messages', '0002_userstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stage',
            field=models.CharField(blank=True, choices=[(None, '-----'), ('trash', 'trash'), ('ban', 'ban'), ('primary', 'primary stage'), ('first_visit', 'first visit')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='UserStage',
        ),
    ]
