# Generated by Django 3.2.23 on 2023-12-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0010_delete_primaryvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryVisit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
    ]
