# Generated by Django 3.2.23 on 2023-12-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0010_delete_primaryvisit'),
        ('first_visit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimaryVisit',
        ),
        migrations.CreateModel(
            name='FirstVisit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
    ]
