# Generated by Django 3.2.25 on 2024-05-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'documentproxy',
                'verbose_name_plural': 'documentsproxys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BANK ACCOUNT', 'Bank account'), ('TRANSFER AGREEMENT', 'Transfer agreement')], max_length=25)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='MainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PASSPORT', 'Passport'), ('INTERNATIONAL PASSPORT', 'International passport'), ('NO_CRIMINAL_RECORD', 'No criminal record'), ('NARCOLOGIST', 'Narcologist'), ('MARIED', 'MARIED'), ('PSYCHOTHERAPIST', 'Psychotherapist'), ('MOTHERS METRIC', "Mother's metric"), ('CHILD METRIC', 'Child metric')], max_length=25)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
