# Generated by Django 3.2.25 on 2024-07-08 14:04

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.CreateModel(
            name='MainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PASSPORT', 'Passport'), ('INTERNATIONAL PASSPORT', 'International passport'), ('NO CRIMINAL RECORD', 'No criminal record'), ('NARCOLOGIST', 'Narcologist'), ('MARIED', 'Maried'), ('PSYCHOTHERAPIST', 'Psychotherapist'), ('MOTHERS METRIC', "Mother's metric"), ('CHILD METRIC', 'Child metric'), ('BANK ACCOUNT', 'Bank account'), ('TRANSFER AGREEMENT', 'Transfer agreement')], max_length=25)),
                ('note', models.TextField(blank=True, null=True, validators=[documents.models.validate_max_length])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=documents.models.directory_path)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_document', to='mothers.mother')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True, validators=[documents.models.validate_max_length])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=documents.models.directory_path)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document', to='mothers.mother')),
            ],
        ),
    ]
