# Generated by Django 3.2.25 on 2024-04-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'document_proxy',
                'verbose_name_plural': 'documents_proxy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MAIN', 'Mafrom ban.inlines import BanInlinein'), ('ACQUIRED FOR PROGRAM', 'Acquired for program'), ('ADDITIONAL', 'Additional')], max_length=25)),
                ('title', models.CharField(choices=[('PASSPORT', 'Passport'), ('INTERNATIONAL PASSPORT', 'International passport'), ('NO_CRIMINAL_RECORD', 'No criminal record'), ('NARCOLOGIST', 'Narcologist'), ('PSYCHOTHERAPIST', 'Psychotherapist'), ('MOTHERS METRIC', "Mother's metric"), ('CHILD METRIC', 'Child metric')], max_length=25)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
