# Generated by Django 3.2.25 on 2024-04-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentproxy',
            options={'verbose_name': 'documentproxy', 'verbose_name_plural': 'documentsproxys'},
        ),
    ]
