# Generated by Django 3.2.25 on 2024-06-17 14:42

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindocument',
            name='file',
            field=models.FileField(upload_to=documents.models.directory_path),
        ),
        migrations.AlterField(
            model_name='maindocument',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maindocument',
            name='title',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('INTERNATIONAL PASSPORT', 'International passport'), ('NO CRIMINAL RECORD', 'No criminal record'), ('NARCOLOGIST', 'Narcologist'), ('MARIED', 'Maried'), ('PSYCHOTHERAPIST', 'Psychotherapist'), ('MOTHERS METRIC', "Mother's metric"), ('CHILD METRIC', 'Child metric')], max_length=25),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='file',
            field=models.FileField(upload_to=documents.models.directory_path),
        ),
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=documents.models.directory_path)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mothers.mother')),
            ],
        ),
    ]
