# Generated by Django 3.2.25 on 2024-06-25 10:13

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20240617_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindocument',
            name='note',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
