# Generated by Django 3.2.25 on 2024-04-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0002_banproxy'),
        ('documents', '0002_auto_20240410_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
    ]
