# Generated by Django 3.2.25 on 2024-06-25 19:41

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_maindocument_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindocument',
            name='note',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
