# Generated by Django 3.2.25 on 2024-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0004_delete_documentproxy'),
        ('documents', '0004_auto_20240411_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_kind',
            field=models.CharField(choices=[(None, '-----'), ('main_docs', 'main documents'), ('acquire_docs', 'acquire documents'), ('additional_docs', 'additional documents')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(choices=[('passport', 'passport')], default='afaf', max_length=255),
            preserve_default=False,
        ),
    ]
