# Generated by Django 3.2.25 on 2024-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_maindocument_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='note',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='maindocument',
            name='note',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='note',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
