# Generated by Django 3.2.25 on 2024-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20240411_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_kind',
            field=models.CharField(choices=[('MAIN DOCS', 'Main documents'), ('ACQUIRE DOCS', 'Acquire documents'), ('ADDITIONAL DOCS', 'Additional documents')], max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('PSYCHOTHERAPIST', 'Psychotherapist')], max_length=255),
        ),
    ]
