# Generated by Django 3.2.25 on 2024-06-26 09:35

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20240625_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindocument',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[documents.models.validate_max_length]),
        ),
    ]
