# Generated by Django 3.2.25 on 2024-06-27 11:54

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
        ('documents', '0007_alter_maindocument_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentProxy',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mothers.mother',),
        ),
        migrations.AlterField(
            model_name='additionaldocument',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[documents.models.validate_max_length]),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[documents.models.validate_max_length]),
        ),
    ]
