# Generated by Django 3.2.25 on 2024-06-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mothers', '0001_initial'),
        ('documents', '0008_auto_20240627_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_document', to='mothers.mother'),
        ),
        migrations.AlterField(
            model_name='maindocument',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_document', to='mothers.mother'),
        ),
        migrations.AlterField(
            model_name='maindocument',
            name='title',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('INTERNATIONAL PASSPORT', 'International passport'), ('NO CRIMINAL RECORD', 'No criminal record'), ('NARCOLOGIST', 'Narcologist'), ('MARIED', 'Maried'), ('PSYCHOTHERAPIST', 'Psychotherapist'), ('MOTHERS METRIC', "Mother's metric"), ('CHILD METRIC', 'Child metric'), ('BANK ACCOUNT', 'Bank account'), ('TRANSFER AGREEMENT', 'Transfer agreement')], max_length=25),
        ),
        migrations.DeleteModel(
            name='RequiredDocument',
        ),
    ]
